package com.peteraraujo.articapi.models.collections.image

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Hash(
    @SerialName("hash_0") val hash0: Boolean? = null,
    @SerialName("hash_1") val hash1: Boolean? = null,
    @SerialName("hash_2") val hash2: Boolean? = null,
    @SerialName("hash_3") val hash3: Boolean? = null,
    @SerialName("hash_4") val hash4: Boolean? = null,
    @SerialName("hash_5") val hash5: Boolean? = null,
    @SerialName("hash_6") val hash6: Boolean? = null,
    @SerialName("hash_7") val hash7: Boolean? = null,
    @SerialName("hash_8") val hash8: Boolean? = null,
    @SerialName("hash_9") val hash9: Boolean? = null,
    @SerialName("hash_10") val hash10: Boolean? = null,
    @SerialName("hash_11") val hash11: Boolean? = null,
    @SerialName("hash_12") val hash12: Boolean? = null,
    @SerialName("hash_13") val hash13: Boolean? = null,
    @SerialName("hash_14") val hash14: Boolean? = null,
    @SerialName("hash_15") val hash15: Boolean? = null,
    @SerialName("hash_16") val hash16: Boolean? = null,
    @SerialName("hash_17") val hash17: Boolean? = null,
    @SerialName("hash_18") val hash18: Boolean? = null,
    @SerialName("hash_19") val hash19: Boolean? = null,
    @SerialName("hash_20") val hash20: Boolean? = null,
    @SerialName("hash_21") val hash21: Boolean? = null,
    @SerialName("hash_22") val hash22: Boolean? = null,
    @SerialName("hash_23") val hash23: Boolean? = null,
    @SerialName("hash_24") val hash24: Boolean? = null,
    @SerialName("hash_25") val hash25: Boolean? = null,
    @SerialName("hash_26") val hash26: Boolean? = null,
    @SerialName("hash_27") val hash27: Boolean? = null,
    @SerialName("hash_28") val hash28: Boolean? = null,
    @SerialName("hash_29") val hash29: Boolean? = null,
    @SerialName("hash_30") val hash30: Boolean? = null,
    @SerialName("hash_31") val hash31: Boolean? = null,
    @SerialName("hash_32") val hash32: Boolean? = null,
    @SerialName("hash_33") val hash33: Boolean? = null,
    @SerialName("hash_34") val hash34: Boolean? = null,
    @SerialName("hash_35") val hash35: Boolean? = null,
    @SerialName("hash_36") val hash36: Boolean? = null,
    @SerialName("hash_37") val hash37: Boolean? = null,
    @SerialName("hash_38") val hash38: Boolean? = null,
    @SerialName("hash_39") val hash39: Boolean? = null,
    @SerialName("hash_40") val hash40: Boolean? = null,
    @SerialName("hash_41") val hash41: Boolean? = null,
    @SerialName("hash_42") val hash42: Boolean? = null,
    @SerialName("hash_43") val hash43: Boolean? = null,
    @SerialName("hash_44") val hash44: Boolean? = null,
    @SerialName("hash_45") val hash45: Boolean? = null,
    @SerialName("hash_46") val hash46: Boolean? = null,
    @SerialName("hash_47") val hash47: Boolean? = null,
    @SerialName("hash_48") val hash48: Boolean? = null,
    @SerialName("hash_49") val hash49: Boolean? = null,
    @SerialName("hash_50") val hash50: Boolean? = null,
    @SerialName("hash_51") val hash51: Boolean? = null,
    @SerialName("hash_52") val hash52: Boolean? = null,
    @SerialName("hash_53") val hash53: Boolean? = null,
    @SerialName("hash_54") val hash54: Boolean? = null,
    @SerialName("hash_55") val hash55: Boolean? = null,
    @SerialName("hash_56") val hash56: Boolean? = null,
    @SerialName("hash_57") val hash57: Boolean? = null,
    @SerialName("hash_58") val hash58: Boolean? = null,
    @SerialName("hash_59") val hash59: Boolean? = null,
    @SerialName("hash_60") val hash60: Boolean? = null,
    @SerialName("hash_61") val hash61: Boolean? = null,
    @SerialName("hash_62") val hash62: Boolean? = null,
    @SerialName("hash_63") val hash63: Boolean? = null
)